In [11]:
!git clone https://github.com/PhonePe/pulse.git

fatal: destination path 'pulse' already exists and is not an empty directory.

In [3]:
#Once created the clone of GIT-HUB repository then,
#Required libraries for the program

import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path="/content/pulse/data/aggregated/transaction/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

['west-bengal',
 'assam',
 'nagaland',
 'rajasthan',
 'delhi',
 'kerala',
 'jammu-&-kashmir',
 'lakshadweep',
 'arunachal-pradesh',
 'meghalaya',
 'uttarakhand',
 'tamil-nadu',
 'himachal-pradesh',
 'puducherry',
 'jharkhand',
 'andhra-pradesh',
 'madhya-pradesh',
 'haryana',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'sikkim',
 'goa',
 'chandigarh',
 'manipur',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'ladakh',
 'bihar',
 'uttar-pradesh',
 'gujarat',
 'punjab',
 'chhattisgarh',
 'mizoram',
 'karnataka',
 'odisha',
 'tripura',
 'telangana']

In [4]:
#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}
for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transacion_type'].append(Name)
              clm['Transacion_count'].append(count)
              clm['Transacion_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Agg_Trans=pd.DataFrame(clm)

In [5]:
agg_trans_list = os.listdir(path)

In [6]:
# To fetch transaction count - transaction type
columns1 = {'State': [], 'Year': [], 'Quarter': [], 'Transaction_type': [], 'Transaction_count': [],
            'Transaction_amount': []}
for state in agg_trans_list:
    cur_state = path + state + "/"
    agg_year_list = os.listdir(cur_state)

    for year in agg_year_list:
        cur_year = cur_state + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            A = json.load(data)

            for i in A['data']['transactionData']:
                name = i['name']
                count = i['paymentInstruments'][0]['count']
                amount = i['paymentInstruments'][0]['amount']
                columns1['Transaction_type'].append(name)
                columns1['Transaction_count'].append(count)
                columns1['Transaction_amount'].append(amount)
                columns1['State'].append(state)
                columns1['Year'].append(year)
                columns1['Quarter'].append(int(file.strip('.json')))

df_agg_trans = pd.DataFrame(columns1)
df_agg_trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,west-bengal,2021,3,Peer-to-peer payments,84353949,2.947997e+11
1,west-bengal,2021,3,Merchant payments,58800005,5.097117e+10
2,west-bengal,2021,3,Recharge & bill payments,37556310,1.604575e+10
3,west-bengal,2021,3,Financial Services,189087,2.134117e+08
4,west-bengal,2021,3,Others,813637,4.269992e+08
...,...,...,...,...,...,...
4129,telangana,2023,1,Merchant payments,830385203,3.699617e+11
4130,telangana,2023,1,Peer-to-peer payments,522865792,1.898814e+12
4131,telangana,2023,1,Recharge & bill payments,86187673,1.027873e+11
4132,telangana,2023,1,Financial Services,326874,4.588212e+08
4133,telangana,2023,1,Others,565916,5.601799e+08

In [7]:
# data frame of aggregated user - to fetch user details
path1 = "/content/pulse/data/aggregated/user/country/india/state/"

agg_user_list = os.listdir(path1)

columns2 = {'State': [], 'Year': [], 'Quarter': [], 'Brands': [], 'Count': [],
            'Percentage': []}
for state in agg_user_list:
    cur_state = path1 + state + "/"
    agg_year_list = os.listdir(cur_state)

    for year in agg_year_list:
        cur_year = cur_state + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            B = json.load(data)
            try:
                for i in B["data"]["usersByDevice"]:
                    brand_name = i["brand"]
                    counts = i["count"]
                    percents = i["percentage"]
                    columns2["Brands"].append(brand_name)
                    columns2["Count"].append(counts)
                    columns2["Percentage"].append(percents)
                    columns2["State"].append(state)
                    columns2["Year"].append(year)
                    columns2["Quarter"].append(int(file.strip('.json')))
            except:
                pass
df_agg_user = pd.DataFrame(columns2)
df_agg_user

            State  Year  Quarter    Brands    Count  Percentage
0     west-bengal  2021        3    Xiaomi  4999610    0.258735
1     west-bengal  2021        3   Samsung  3933160    0.203545
2     west-bengal  2021        3      Vivo  3037405    0.157189
3     west-bengal  2021        3      Oppo  2144589    0.110985
4     west-bengal  2021        3    Realme  1644196    0.085089
...           ...   ...      ...       ...      ...         ...
6727    telangana  2020        4  Motorola   444416    0.027902
6728    telangana  2020        4   OnePlus   436917    0.027431
6729    telangana  2020        4    Huawei   376296    0.023625
6730    telangana  2020        4    Lenovo   231688    0.014546
6731    telangana  2020        4    Others   966570    0.060684

[6732 rows x 6 columns]

In [8]:
# Data frame of map transactions - to fetch map details
path2 = "/content/pulse/data/map/transaction/hover/country/india/state/"

map_trans_list = os.listdir(path2)

columns3 = {'State': [], 'Year': [], 'Quarter': [], 'District': [], 'Count': [],
            'Amount': []}

for state in map_trans_list:
    cur_state = path2 + state + "/"
    map_year_list = os.listdir(cur_state)

    for year in map_year_list:
        cur_year = cur_state + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            C = json.load(data)

            for i in C["data"]["hoverDataList"]:
                district = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns3["District"].append(district)
                columns3["Count"].append(count)
                columns3["Amount"].append(amount)
                columns3['State'].append(state)
                columns3['Year'].append(year)
                columns3['Quarter'].append(int(file.strip('.json')))

df_map_trans = pd.DataFrame(columns3)
df_map_trans

,State,Year,Quarter,District,Count,Amount
0,west-bengal,2021,3,south twenty four parganas district,8148035,1.700326e+10
1,west-bengal,2021,3,purba bardhaman district,4895497,9.701090e+09
2,west-bengal,2021,3,uttar dinajpur district,2833025,7.139308e+09
3,west-bengal,2021,3,kalimpong district,195057,4.656760e+08
4,west-bengal,2021,3,murshidabad district,10931440,2.574891e+10
...,...,...,...,...,...,...
16827,telangana,2023,1,medchal malkajgiri district,256028955,3.824232e+11
16828,telangana,2023,1,karimnagar district,30992192,6.009632e+10
16829,telangana,2023,1,mancherial district,20046172,3.690725e+10
16830,telangana,2023,1,siddipet district,24660934,4.840637e+10
16831,telangana,2023,1,khammam district,31419139,6.287036e+10

In [9]:
# Data frame of map user - to fetch map user details
path3 = "/content/pulse/data/map/user/hover/country/india/state/"

map_user_list = os.listdir(path3)

columns4 = {"State": [], "Year": [], "Quarter": [], "District": [],
            "RegisteredUser": [], "AppOpens": []}

for state in map_user_list:
    cur_state = path3 + state + "/"
    map_year_list = os.listdir(cur_state)

    for year in map_year_list:
        cur_year = cur_state + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            D = json.load(data)

            for i in D["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appOpens = i[1]['appOpens']
                columns4["District"].append(district)
                columns4["RegisteredUser"].append(registereduser)
                columns4["AppOpens"].append(appOpens)
                columns4['State'].append(state)
                columns4['Year'].append(year)
                columns4['Quarter'].append(int(file.strip('.json')))

df_map_user = pd.DataFrame(columns4)
df_map_user

,State,Year,Quarter,District,RegisteredUser,AppOpens
0,west-bengal,2021,3,south twenty four parganas district,1383020,23765288
1,west-bengal,2021,3,purba bardhaman district,847622,15020358
2,west-bengal,2021,3,uttar dinajpur district,425320,10453927
3,west-bengal,2021,3,kalimpong district,40581,1787640
4,west-bengal,2021,3,murshidabad district,1342984,21103271
...,...,...,...,...,...,...
16831,telangana,2023,1,medchal malkajgiri district,3787461,32008875
16832,telangana,2023,1,karimnagar district,718193,31218292
16833,telangana,2023,1,mancherial district,453837,37525510
16834,telangana,2023,1,siddipet district,549109,52595211
16835,telangana,2023,1,khammam district,790500,42709479

In [10]:
# Data frame of top transactions
path4 = "/content/pulse/data/top/transaction/country/india/state/"

top_trans_list = os.listdir(path4)
columns5 = {'State': [], 'Year': [], 'Quarter': [], 'Pincode': [], 'Transaction_count': [],
            'Transaction_amount': []}

for state in top_trans_list:
    cur_state = path4 + state + "/"
    top_year_list = os.listdir(cur_state)

    for year in top_year_list:
        cur_year = cur_state + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            E = json.load(data)

            for i in E['data']['pincodes']:
                name = i['entityName']
                count = i['metric']['count']
                amount = i['metric']['amount']
                columns5['Pincode'].append(name)
                columns5['Transaction_count'].append(count)
                columns5['Transaction_amount'].append(amount)
                columns5['State'].append(state)
                columns5['Year'].append(year)
                columns5['Quarter'].append(int(file.strip('.json')))
df_top_trans = pd.DataFrame(columns5)
df_top_trans

,State,Year,Quarter,Pincode,Transaction_count,Transaction_amount
0,west-bengal,2021,3,700009,39926216,7.719692e+10
1,west-bengal,2021,3,711102,9206955,1.493093e+10
2,west-bengal,2021,3,742133,2292921,4.859875e+09
3,west-bengal,2021,3,734006,1705085,3.717672e+09
4,west-bengal,2021,3,700156,1306087,1.534276e+09
...,...,...,...,...,...,...
8205,telangana,2023,1,500039,20088858,2.935919e+10
8206,telangana,2023,1,500055,19030473,2.951810e+10
8207,telangana,2023,1,500016,18996218,2.357788e+10
8208,telangana,2023,1,502032,17936827,2.769381e+10
8209,telangana,2023,1,500084,17271081,2.305162e+10

In [12]:
# Data frame of top users
path5 = "/content/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path5)
columns6 = {'State': [], 'Year': [], 'Quarter': [], 'Pincode': [],
            'RegisteredUsers': []}

for state in top_user_list:
    cur_state = path5 + state + "/"
    top_year_list = os.listdir(cur_state)

    for year in top_year_list:
        cur_year = cur_state + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            F = json.load(data)

            for i in F['data']['pincodes']:
                name = i['name']
                registeredUsers = i['registeredUsers']
                columns6['Pincode'].append(name)
                columns6['RegisteredUsers'].append(registeredUsers)
                columns6['State'].append(state)
                columns6['Year'].append(year)
                columns6['Quarter'].append(int(file.strip('.json')))
df_top_user = pd.DataFrame(columns6)
df_top_user

            State  Year  Quarter Pincode  RegisteredUsers
0     west-bengal  2021        3  711101           123732
1     west-bengal  2021        3  700006           105800
2     west-bengal  2021        3  700135            94553
3     west-bengal  2021        3  700156            87746
4     west-bengal  2021        3  700039            82997
...           ...   ...      ...     ...              ...
8206    telangana  2023        1  500037           290149
8207    telangana  2023        1  500039           281889
8208    telangana  2023        1  502032           265962
8209    telangana  2023        1  506002           263096
8210    telangana  2023        1  500013           259941

[8211 rows x 5 columns]

In [13]:
# Coverting Data frames to csv files
df_agg_trans.to_csv('agg_trans.csv',index=False)
df_agg_user.to_csv('agg_user.csv',index=False)
df_map_trans.to_csv('map_trans.csv',index=False)
df_map_user.to_csv('map_user.csv',index=False)
df_top_trans.to_csv('top_trans.csv',index=False)
df_top_user.to_csv('top_user.csv',index=False)